# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
array1 = np.array([1, 2, 3])


# Create a 2-dimensional NumPy array using np.array()
array2 = np.array([
    [4, 5, 6], 
    [4, 5, 6]
])


# Create a 3-dimensional Numpy array using np.array()
array3 = np.array([
    [[12, 52,566]], 
    [[6, 34, 23]], 
    [[83, 23, 19.4]],
])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

array1.ndim, array1.size, array1.shape, type(array1), array1.dtype

(1, 3, (3,), numpy.ndarray, dtype('int64'))

In [4]:
# Attributes of 2-dimensional array

array2.ndim, array2.size, array2.shape, type(array2), array2.dtype

(2, 6, (2, 3), numpy.ndarray, dtype('int64'))

In [5]:
# Attributes of 3-dimensional array

array3.ndim, array3.size, array3.shape, type(array3), array3.dtype

(3, 9, (3, 1, 3), numpy.ndarray, dtype('float64'))

In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(array1, index=["Value1", "Value2", "Value3"], columns=["Column Name"])
df

In [ ]:
# Create an array of shape (10, 2) with only ones
array_10_2 = np.random.randint(1, size=(10, 2))
array_10_2

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
array_7_2_3 = np.zeros((7, 2, 3))
array_7_2_3

In [ ]:
# Create an array within a range of 0 and 100 with step 3
array_range_step = np.arange(0, 100, 3)
array_range_step

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_rand_7_2 = np.random.randint(0, 10, size=(7, 2))
array_rand_7_2

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_rand_floats_3_5 = np.random.uniform(0, 1, size=(3, 5))
array_rand_floats_3_5

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, size=(4, 6))

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_3_7 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
array_3_7, np.unique(array_3_7)

In [ ]:
# Find the 0'th index of the latest array you created
array_3_7[0]

In [ ]:
# Get the first 2 rows of latest array you created
array_3_7[:2]

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
array_3_7[:, :2]

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_0_10 = np.random.randint(0, 10, size=(3, 5))
array_1_1 = np.ones((3, 5))

In [ ]:
# Add the two arrays together
array_add = array_0_10 + array_1_1

In [ ]:
# Create another array of ones of shape (5, 3)
array_1_2 = np.ones((5, 3))

In [ ]:
# Try add the array of ones and the other most recent array together
array_add + array_1_2.T

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
array_1_3_5 = np.ones((3, 5))

In [ ]:
# Subtract the new array of ones from the other most recent array
array_1_3_5 - array_1_2.T

In [ ]:
# Multiply the ones array with the latest array
array_1_3_5 * array_add

In [ ]:
# Take the latest array to the power of 2 using '**'
array_add ** 2

In [ ]:
# Do the same thing with np.square()
np.square(array_add)

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(array_add)

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(array_add)

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(array_add)

In [ ]:
# Find the standard deviation of the latest array
np.std(array_add)

In [ ]:
# Find the variance of the latest array
np.var(array_add)

In [ ]:
# Reshape the latest array to (3, 5, 1)
np.reshape(array_add, (3, 5, 1))

In [ ]:
# Transpose the latest array
array_add.T

What does the transpose do?

In [7]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_3_3 = np.random.randint(0, 10, size=(3, 3))
array_3_2 = np.random.randint(0, 10, size=(3, 2))

In [9]:
# Perform a dot product on the two newest arrays you created
np.dot(array_3_3, array_3_2)

array([[ 49,  78],
       [116,  79],
       [ 62,  91]])

In [10]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_1_4_3 = np.random.randint(0, 10, size=(4, 3))
array_2_4_3 = np.random.randint(0, 10, size=(4, 3))

In [13]:
# Perform a dot product on the two newest arrays you created
# np.dot(array_1_4_3, array_2_4_3)

It doesn't work. How would you fix it?

In [14]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_1_4_3, array_2_4_3.T)

array([[ 63,  68,  50,   9],
       [ 77, 103,  90,  30],
       [ 91, 112,  84,  21],
       [ 70,  96,  86,  30]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [18]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_1_8_4 = np.random.randint(0, 10, size=(8, 4))
array_2_8_4 = np.random.randint(0, 10, size=(8, 4))
array_1_8_4, array_2_8_4

(array([[7, 8, 8, 7],
        [3, 0, 6, 9],
        [9, 4, 9, 2],
        [5, 5, 6, 6],
        [7, 4, 7, 2],
        [6, 5, 8, 9],
        [4, 5, 3, 6],
        [5, 8, 3, 4]]),
 array([[7, 9, 5, 6],
        [4, 3, 3, 1],
        [1, 9, 5, 6],
        [9, 6, 1, 7],
        [3, 5, 6, 6],
        [3, 9, 2, 3],
        [3, 2, 8, 9],
        [8, 5, 0, 6]]))

In [19]:
# Compare the two arrays with '>'
array_1_8_4 > array_2_8_4

array([[False, False,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True, False],
       [False, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True,  True, False, False],
       [False,  True,  True, False]])

What happens when you compare the arrays with `>`?

In [20]:
# Compare the two arrays with '>='
array_1_8_4 >= array_2_8_4

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True, False],
       [False, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True,  True, False, False],
       [False,  True,  True, False]])

In [23]:
# Find which elements of the first array are greater than 7
array_1_8_4 > 7

array([[False,  True,  True, False],
       [False, False, False,  True],
       [ True, False,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False],
       [False,  True, False, False]])

In [24]:
# Which parts of each array are equal? (try using '==')
array_1_8_4 == array_2_8_4

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
# Sort one of the arrays you just created in ascending order
np.sort(array_1_8_4, axis=0)

array([[3, 0, 3, 2],
       [4, 4, 3, 2],
       [5, 4, 6, 4],
       [5, 5, 6, 6],
       [6, 5, 7, 6],
       [7, 5, 8, 7],
       [7, 8, 8, 9],
       [9, 8, 9, 9]])

In [31]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_1_8_4)

array([[0, 3, 1, 2],
       [1, 0, 2, 3],
       [3, 1, 0, 2],
       [0, 1, 2, 3],
       [3, 1, 0, 2],
       [1, 0, 2, 3],
       [2, 0, 1, 3],
       [2, 3, 0, 1]])

In [32]:
# Find the index with the maximum value in one of the arrays you've created
np.max(array_1_8_4)

9

In [33]:
# Find the index with the minimum value in one of the arrays you've created
np.min(array_1_8_4)

0

In [34]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.max(array_1_8_4, axis=1)

array([8, 9, 9, 6, 7, 9, 6, 8])

In [35]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.min(array_1_8_4, axis=0)

array([3, 0, 3, 2])

In [37]:
# Create an array of normally distributed random numbers
np.random.normal(0, 10, size=(3, 3))

array([[ -3.1658085 ,   0.09839291, -12.81723128],
       [  4.43991843,  -6.72644598,  -4.38778207],
       [  2.55402665,   8.08354468, -14.45815724]])

In [42]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.